### ISSUE TITLE
check_yaml function creation

### ISSUE THREAD

**Issue by tingum** [prlitics/vrrr#1]
Similar to check_state, I think we'll need a function that ensures we have the .yaml file completed and ready to use. I'm going to follow the same structure you have for check_state.

**Comment by prlitics** [comment]
Excellent idea, I agree. I have a couple ideas how to do this:

1. Make a list similar to that used in `check_states` (which is located in `helpful_lists.R`) that has the list of states that we've finished. I think it would work for now because we're not dealing with versioning at the moment. But that would have some problems down the road 'cus people would need to reinstall the package to get new versions of the list.

2. Make a named list that references state names and postal codes to the string attached to the file name: e.g.,   
`state_key<-c("fl"="florida", "florida"="florida",....)` and have it look through the folder of yamls based on the state name people put in.  So the pseudo code would be like:

```
vrr_read(states="florida")
check_state(states)

check_yaml(states)
```
and `check_yaml(states)` would look like:

```
check_yaml<-function(states){
currrent_dir<-getwd()
setwd("where the yamls live")

if(tolower(states) %in% names(state_key)){
  state_yaml<- paste(state_key[tolower(states)],".yaml",sep=""}
 called_yaml<- yaml:: yaml.load_file(state_yaml)
}else{
stop("Some warning about how their state input isn't recognized")}

setwd(current_dir)
called_yaml}
```

This assumes that we'll put all the state names in lowercase in the yaml folder, which, IMHO, might be the easiest way to handle things going forward.

**Comment by prlitics** [comment]
Small question on this topic: How are the yaml's formatted for states with spaces in the name? Is it, e.g., `new hampshire.yaml` or `newhampshire.yaml`?

**Comment by tingum** [comment]
Currently, they are formatted as new_hampshire.yaml but I realized yesterday that would present a problem with our code. I was going to go in today and format them to be newhampsire.yaml and then we can add a line of code in the functions after toLower to remove any spaces as well.

Thoughts? Is that what you were thinking or should we add a line that adds the underscore in?

________________________________

**Comment by prlitics** [comment]
Perfect! I was thinking no space as well. And we could add a remove space thing, but we could also just use the named list to do so (which is needed to convert from postal code to full state name). 

I've committed some edits to check_yaml that'll handle the `state` input. I also tweaked the flow and wording of the error message. You should be able to see that by fetching my branch. (I think. Learning by the seat of my pants here lol). 

The reason I changed the error to what it is now is twofold: 1: I want them to be as descriptive as possible for the end-user. It saves us (or whoever inherits the project) headaches down the road if people can glean enough from the output to figure out the next step rather than coming here and making an issue saying "what the hell does exception 169 mean?" (or some other gobbledygook that base R might spit out). But also, 2: It sets us up for what I'm envisioning for the project. There's a higher level conversation we're going to need to have with Mike on Wednesday, but I'm thinking that there should be a function that's run on package installation that goes to the vrrr repository and gathers all of the yamls collected so far and makes them available locally from the package. (Sort of like what happens with the `nyc flights` data in dplyr). That function should be documented and easy enough to use so that, periodically, the user can run it and fetch updates to the yamls without having to reinstall the whole blooming package. If Mike agrees, then I'll add a second line to the new warning message for `check_yaml` advising them to run this function to check for updates. Something like "run update_yamls() to see if VEST has added documentation for the requested file in its repository."

**Comment by tingum** [comment]
You read my mind on using the state list to correct the spaces. After I sent that initial email I realized that would be the best course of action instead, and made some changes (on my branch) to the helpful_lists.R file.

I'll take a look at the changes to the error messages, but that all sounds good to me. Also, I think that being able to host yamls locally in the package would be useful and I hope we can make that happen.

For now, I'm going to push all my changes up to the master branch (also flying by the seat of my pants here, lol) to make sure everything is still meshing well. Then, I'll try to move on in the coding based on what Reggie has as its next steps. I'm assuming now we can begin the process of using the yaml with the state file, but I'll see if we're missing anything in between.

See you on Github!
-J
________________________________
